# Configuration file in YAML format
# https://en.wikipedia.org/wiki/YAML#Basic_components

# specify your NHL.TV account email
# email: johndoe@gmail.com
email:
# and password
# password: johnDoesNhlTvPassword
password:

# dates for matches will be shown in this time zone
# default is set the way that all matches for the given day
# are within 1 day in this timezone
# should probably leave this as is
matchTimeZone: America/Denver

# do not jump into the middle of a game, always start from beginning
# does not have effect if there are previous files downloaded - will continue
# downloading from where it ended
playLiveGamesFromStart: true

# set your favourite teams, will highlight them in the list
# get abbreviations from
# https://statsapi.web.nhl.com/api/v1/teams
# favouriteTeams: [WSH, PIT, TBL]
favouriteTeams: []








# ===================================
# everything below is NOT working yet
# ===================================

# do not show other teams' games in case favorite teams are set
skipOtherTeams: true

# this can be used for automatic cron job download once a day
# will select preferred feed for favourite team
# or first available if the only found game does not include one of
# `favouriteTeams`
startDownloadingIfSingleGameFound: true
