# Configuration file in YAML format
# https://en.wikipedia.org/wiki/YAML#Basic_components

# specify your NHL.TV account email
email:
# and password
password:

# do not jump into the middle of a game, always start from beginning
playLiveGamesFromStart: true

# set your favourite teams, will highlight them in the list
# get abbreviations from
# https://statsapi.web.nhl.com/api/v1/teams
# favouriteTeams: [WSH, PIT, TBL]
favouriteTeams: []

# ===================================
# everything below is NOT working yet
# ===================================

# do not show other teams' games in case favorite teams are set
skipOtherTeams: true

# this can be used for automatic cron job download once a day
# will select preferred feed for favourite team
# or first available if the only found game does not include one of
# `favouriteTeams`
startDownloadingIfSingleGameFound: true
