version: "3"

services:
  nhltv:
    container_name: "nhltv"
    stdin_open: true
    tty: true
    build: .
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
      # logs, session data
      - ./tmp:/app/tmp
      - ${DOWNLOAD_DIR}:/app/video
      - node_modules:/app/node_modules

volumes:
  node_modules:
    # driver: local  # is already local by default
