version: "3"

services:
  nhltv:
    container_name: "nhltv"
    stdin_open: true
    tty: true
    build: .
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      # logs, session data
      - ./tmp:/usr/src/app/tmp
      - ${DOWNLOAD_DIR}:/usr/src/app/video
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
    # driver: local  # is already local by default
